### ISSUE TITLE
Add remoteStorage

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/applications#108]
https://github.com/fkooman/php-remote-storage

**Comment by skddc** [comment]
Would love to see this happen!

One question: if we would fund this, would you open-source the Docker files and such?

**Comment by pierreozoux** [comment]
Yes, of course :) (you can see our [politic](https://github.com/indiehosters/applications))

We always try to PR the official repo, and even better, make it an official image.

As a reference:
 - [piwik](https://github.com/piwik/docker-piwik) ([PR](https://github.com/docker-library/official-images/pull/1203))
 - [Rocket.Chat](https://github.com/docker-library/official-images/commits?author=pierreozoux)
 - [ownCloud](https://github.com/docker-library/owncloud/commits?author=pierreozoux)

And then, the more you fund us, the faster it is to make all this happen :)
(In the case of remoteStorage, I'm not sure official docker image would accept, but we can still try)

**Comment by skddc** [comment]
Awesome! Brb, posting bounty. :)

**Comment by pierreozoux** [comment]
Awesome!
https://microblog.pierre-o.fr/2015/our-first-bounty-has-been-met-please-welcome-remotestorage-as

Thanks :) (I hope I'll have enough time this week, I'll let you know)

**Comment by skddc** [comment]
Cool, thanks!

**Comment by pierreozoux** [comment]
It is now here: https://github.com/indiehosters/remoteStorage

Let me know if you want me to PR anywhere, or if you have any comments!

**Comment by skddc** [comment]
I added a comment to the website, because it says it's not available yet. Also PRed the Docker repo with an up-to-date logo.
