### ISSUE TITLE
Add gitlab

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/applications#3]
https://registry.hub.docker.com/search?q=gitlab&searchfield=

https://github.com/search?utf8=%E2%9C%93&q=docker+gitlab&type=Repositories&ref=searchresults

**Comment by michielbdejong** [comment]
GitLab is quite a complicated application to install, I think, have to investigate which image from https://registry.hub.docker.com/search?q=gitlab&s=downloads would suit our needs.

**Comment by pierreozoux** [comment]
Duplicate #101

**Comment by almereyda** [comment]
I suppose rather #101 should be closed and this #3 reopened.

From https://github.com/indiehosters/applications/issues/101#issuecomment-213632390

---

I have good experiences with https://github.com/sameersbn/docker-gitlab/.
