### ISSUE TITLE
  Store inmutable php files outside /data in lamp-based images

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/applications#45]
moved from https://github.com/michielbdejong/snickers-applications/issues/14

**Comment by pierreozoux** [comment]
Is it still current?

**Comment by michielbdejong** [comment]
I think in your images most immutable php files are outside /data, although this can give the problem that for some applications (especially wordpress) people can't upgrade or install certain plugins, so it requires some care.

**Comment by niktrix** [comment]
there will be saparate folder for every application to take care of

wordpress: wp-content

need to find out all the data folder for the respective applicaitions

**Comment by pierreozoux** [comment]
It's already done on my wordpress image. wp-content is mounted on the host. So we'll close this.
