### ISSUE TITLE
Automate Known user setup

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/applications#47]
Moved from https://github.com/michielbdejong/snickers-applications/issues/7

**Comment by pierreozoux** [comment]
Is it still current?

**Comment by michielbdejong** [comment]
I think now when you add a new Known container, you get the setup screen where you have to put in the database server IP address etc. So by adding those settings (including things like the title of the blog) either as ENV vars or in the config.php file, you could automate that step.

**Comment by michielbdejong** [comment]
but it's not something I'm currently working on anymore, so unless you want to do it, you can close the issue.

**Comment by pierreozoux** [comment]
It's already working on mine. closing
