### ISSUE TITLE
Add cozy

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/applications#48]
Moved from https://github.com/michielbdejong/snickers-applications/issues/5

**Comment by pierreozoux** [comment]
Where are you on this?

**Comment by michielbdejong** [comment]
The cozy/full image from the registry works out of the box, but not behind a proxy. Yesterday I was thinking to just change snickers so that it does a https request to the backend (and then there can be a self-signed cert inside the container). Other than that, I think it's using iframes to high ports, so that would also require some special care, we probably need to put one SNI offloader for each port it will use (or the first 10 it will use, so you can at least install 10 apps).

**Comment by michielbdejong** [comment]
Other option would be to assign one IP address to each Cozy instance, and route that whole IP address straight to the container. I wonder how OVH do this, maybe I'll ask for some advice in the cozycloud irc channel about this.

**Comment by pierreozoux** [comment]
I think I'll help them split this image in smaller ones. And then the smaller one will be without https. We'll see.

**Comment by pierreozoux** [comment]
duplicate #96
