### ISSUE TITLE
Move wordpress as a new repo

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/applications#58]

**Comment by pierreozoux** [comment]
Almost done.
@michielbdejong can I recreate https://hub.docker.com/r/indiehosters/wordpress/ without problems for you?

Thanks!

**Comment by michielbdejong** [comment]
Yes, most of my domains pull from https://hub.docker.com/r/indiehosters/lamp/ and https://hub.docker.com/r/indiehosters/wordpress-mysql/ IIRC
