### ISSUE TITLE
Add mailing liste

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/applications#98]
Transferred from: https://github.com/IndiePaaS/IndiePaaS/issues/35

**Comment by pierreozoux** [comment]
Any idea for an app for that?

**Comment by almereyda** [comment]
What about http://ponymail.info/ + https://github.com/alexbarcelo/docker-mailman3?

**Comment by rikmendes** [comment]
what about SYMPA mailing list ? 
https://www.sympa.org/

to my experience this is far better than mailman & other mailing list apps.

**Comment by pierreozoux** [comment]
Ok, I think I'll close that as we offer Discourse already and it does a better job than any other mailing software.

If you have a really good argument against it, we can discuss :)
